name: interpolator
version: '0.1'
author: Dan Fithian <daniel.m.fithian@gmail.com>
maintainer: TVision Insights
license: MIT
synopsis: 'Runtime interpolation of environment variables in records using profunctors'
description: |
  Runtime interpolation of environment variables in records using profunctors. See
  https://github.com/tvision-insights/interpolator/README.md.
category: Data

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PackageImports
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wredundant-constraints
  - -fwarn-tabs
  - -O2

dependencies:
  - aeson
  - base < 5.0
  - containers
  - either
  - mono-traversable
  - mtl
  - profunctors
  - product-profunctors
  - QuickCheck
  - template-haskell
  - text

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - interpolator
